name: GatewayDockerPublish

on:
  push:
    branches:
      - main
    paths:
      - "server/gateway/**"
  workflow_dispatch:
    
jobs:
  build:
    uses: ./.github/workflows/docker-publish.yml
    with:
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}
      IMAGE_NAME: gateway