name: IdentityDockerPublish

on:
  push:
    branches:
      - main
    paths:
      - "server/identity/**"
      - "server/common/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/docker-publish.yml
    with:
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}
      IMAGE_NAME: identity
      DOCKERFILE: ./server/identity/Dockerfile