name: SchedulerDockerPublish

on:
  push:
    branches:
      - main
    paths:
      - "server/scheduler/**"
      - "server/common/**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker-publish.yml
    permissions:
      packages: write
      id-token: write
    with:
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}
      IMAGE_NAME: scheduler
